### PR TITLE
build(types): add Betterer rule for strict mode and fix a few issues

### PR DESCRIPTION
**Pull request by phenomnomnominal**
Added [Betterer](https://github.com/phenomnomnominal/betterer) and the `@betterer/typescript` test, with snapshot of current strict mode issues. 

You could integrate the `betterer` command into your build to make sure that it doesn't get worse!

Also fixed a few issues, hopefully didn't break anything 😅

### CODE REVIEW

**Comment by zakhenry** [comment]
Hey awesome, thanks @phenomnomnominal - I'll take a closer look at this tomorrow morning. Something seems up with the config as codecov bot is supposed to report the coverage change :/

**Comment by zakhenry** [comment]
@phenomnomnominal is there a way to have the CI enforce Betterer? It seems that it would be nice to have subsequent CI builds fail if the someone make a PR that is making things worse(er)

**Comment by zakhenry** [comment]
Verified (locally) that code coverage remains at 100%, merging. I'll fix up codecov separately.

**Comment by phenomnomnominal** [comment]
> @phenomnomnominal is there a way to have the CI enforce Betterer? It seems that it would be nice to have subsequent CI builds fail if the someone make a PR that is making things worse(er)

All you need to do is run `betterer` in your CI build. I couldn't easily see which command was run, but it should be simple! It'll throw exit code `1` if it gets worse, and `0` if it stays the same or gets better(er)

**Comment by zakhenry** [comment]
Ah sweet, I'll add that in, thanks!

**Comment by zakhenry** [comment]
raised https://github.com/cloudnc/observable-webworker/pull/43 to do just this ^

**Pull request merged**
